### ISSUE TITLE
Support the latest Angular LTS 11

### ISSUE THREAD

**Issue by aturlov-at-work** [microsoft/powerbi-client-angular#10]
Business applications are rarely written with the latest versions of frameworks, but rather with the latest LTS (long term support) versions. According to https://angular.io/guide/releases#support-policy-and-schedule Angular 12 is in active development and not LTS but this package only supports Angular 12 which is unacceptable for commercial development. There should be an officially released package that targets Angular 11 which is the latest LTS version.

**Comment by may-hartov** [comment]
We have released a new version of powerbi-client-angular to support Angular 11 Applications, please use version >= 2.0.0
