### ISSUE TITLE
Problems in using <powerbi-report> in Angular application having routes with RouteReuseStrategy

### ISSUE THREAD

**Issue by subodhsgod** [microsoft/powerbi-client-angular#19]
**Issue in a nutshell** - We are trying explore this library but it's blocking us because it uses iframe to house the report.

**Details** -
Like README.md file mentions, this library/component allows to "embeds" Power BI reports in Angular web application, hence it's using iframe (i.e. to embed). However we are running into problems in consuming it due to usage of iframe.

Just like any standard Angular web application we are using routing in our application.
  Refer: https://angular.io/guide/routing-overview

Plus, we have Route Reuse Strategy in place, so that routes are not destroyed when user switches between routes
  Refer: https://angular.io/api/router/RouteReuseStrategy

When we use this component in one of our routes, since it’s not a generating “inline content” (but generates iframe), we see below:
- When user switches to different route, “power bi iframe” gets destroyed and
- When user comes back to that route, iframe is recreated again

Iframe gets created and destroyed as many times as user switches between routes, degrading overall user experience as:
- User loses the context due to reloading of report in iframe
- User sees a loading happening again from scratch
- Additionally, it increases network traffic degrading performance

Questions:
1. Do you have any ways to address above problems?
2. Do you have any plans to update this library/component with native Angular implementation?

**Comment by good-coding-angular** [comment]
Also as a possible consequence of this behaviour when you click the back button in the browser you end up on an empty page.

**Comment by jaspreet1234567** [comment]
@good-coding-angular - Did you find the solution to this problem (end up with an empty page when we click on the back button)?

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is a feature request, please add it in the following link where we can collect votes: https://ideas.fabric.microsoft.com . If the feature is already there, you can add a vote.
