### ISSUE TITLE
Problems in using <powerbi-report> in Angular application using Popup Window (New Browser Window)

### ISSUE THREAD

**Issue by subodhsgod** [microsoft/powerbi-client-angular#22]
Since we are not able to use _powerbi-report_ component in our Angular Web App which is having routes, due to blocker issue with _powerbi-report_ component. Refer - https://github.com/microsoft/powerbi-client-angular/issues/19

Hence, I went ahead and explored _powerbi-report_ component using Popup Window approach (New Browser window opened using _window.open()_ API of Browser).

I have extended this GitHub repository to have Popup Window and render _powerbi-report_ component also in Popup Window. Added console logs when CustomEvent is received. That is -
```
eventHandlersMap = new Map<string, (event?: service.ICustomEvent<any>) => void>([
  ['loaded', () => console.log('Report has loaded')],
  ['rendered', () => { console.log('Report has rendered'); }],
  ['visualClicked', (params) => console.log('visual clicked', params)],
  ['pageChanged', (event) => console.log('page changed', event)],
  [
    'error', (event?: service.ICustomEvent<any>) => {
      if (event) {
        console.error('error event', event.detail);
      }
    }
  ]
]);
```

Unfortunately, I found one more blocker, that is - Events coming out of _powerbi-report_ component are not reaching the parent component when _powerbi-report_ component is in Popup Window. Events reach parent component only when _powerbi-report> component is in same page.

Pl. refer attached screenshot for the issue -
- The _CustomEvent_ marked in below screenshot (as yellow highlight), as _visualClicked_, is reaching parent component when _powerbi-report_ component is on same page.
- The same is not happening when _powerbi-report_ component is in Popup Window, here nothing gets logged in Browser console, as Events are not reaching parent component.

![Power-BI-Events](https://user-images.githubusercontent.com/76988179/163318087-b903eb76-49a0-49af-9706-cc0212973490.jpg)

**Comment by arshadazeem** [comment]
Hi @parth-007, do you have any feedback or thoughts on how to work around this?

**Comment by subodhsgod** [comment]
@arshadazeem - As discussed in a call, please find attached the source code which is copy of this repository and I have modified it to depicts the problem we are facing here - [powerbi-client-angular-popup-window-main.zip](https://github.com/microsoft/powerbi-client-angular/files/8528480/powerbi-client-angular-popup-window-main.zip)

**Comment by parth-007** [comment]
Hey @arshadazeem ,
I am not maintaining this repository now. But will check and update here, if I find anything.

Hope that helps.
Thanks.

**Comment by ayeshurun** [comment]
Thank you for reporting this issue. We closed the issue because it's old.
