### ISSUE TITLE
How to print and fullscreen

### ISSUE THREAD

**Issue by syntaxerror00100** [microsoft/powerbi-client-angular#27]
Is there a way to fullscreen and print the report?

**Comment by daniel-seitz** [comment]
1. Use this in your component to get a ref to your Report:
@ViewChild(PowerBIReportEmbedComponent) reportRef!: PowerBIReportEmbedComponent;

2. call one of these:
this.reportRef.getReport().fullscreen();
this.reportRef.getReport().print();

There are other methods too, please search for the js documentation.

**Comment by mohsinjamadar** [comment]
Hi @daniel-seitz 

I am getting reportRef object as undefined all the time.

I have followed the documentation keenly, still no luck

could you help me in this

**Comment by daniel-seitz** [comment]
Hi @mohsinjamadar this kind of question belongs to stackoverflow and not here. Post your question there.
Also I cant say anything without seeing some code, here some things to check:

1. are you sure that you use this lib? 
2. do you have the <powerbi-report> tag in your template?
3. do you import correctly in your component? 
       import { ViewChild } from '@angular/core';    
       import { PowerBIReportEmbedComponent } from 'powerbi-client-angular';

Maybe the report needs to get the embedConfig first and at least load a report.

Other than that its really hard to say.
