### ISSUE TITLE
Version 3.0.0 to NPM?

### ISSUE THREAD

**Issue by Log4TurtleShell** [microsoft/powerbi-client-angular#28]
Is version 3.0.0 going to be published to NPM? It is specified in package.json, and causes the demo app to fail unless you change it to 2.0.1. I was able to get the demo app to work, however I cannot get version 2.0.1 to work with my existing project. I think 3.0.0 may work with my project.

**Comment by hamfastgamgee** [comment]
@may-hartov Can you please publish the new version?  Our app is trying to add PowerBI support, but relying on ViewEngine is holding our app back.  Thanks!

**Comment by hamfastgamgee** [comment]
Any update here?  Angular 15 is on the way with support for Ivy only.

**Comment by JAspeling** [comment]
Please publish version 3 to npm. It is being referenced in the package.json, and the demo app is not working because of this.

**Comment by maxs-rose** [comment]
We also need this published to version 3 as its holding back our project as well

**Comment by PBentAtQICGlobal** [comment]
Also needed here

**Comment by hamfastgamgee** [comment]
I see a version 3.0.0 up on npm now, but the package appears to be broken.  It contains only package.json and nothing else.

**Comment by hamfastgamgee** [comment]
It appears that version has now been pulled.  I guess I'm hoping this means someone is trying to make it build?  A comment from a contributor would be really nice, wink wink. :)

**Comment by rygar08** [comment]
Any eta on version 3.0 in npm?

**Comment by hamfastgamgee** [comment]
Any updates here?  Angular 15 is out now.  Would love to relegate ngcc to the dustbin of history. :)

**Comment by KotanaSai21** [comment]
We are currently working on it and planning to release the new version shortly. Thank you for your patience!

**Comment by hamfastgamgee** [comment]
It appears version 3.0.3 has been published as a beta package in npm.  Seems to work in my testing. :)

**Comment by Nassim-89** [comment]
> 

Seems to work with 3.0.5 (beta) as well for now.

**Comment by orshemesh16** [comment]
Hello, version 3.0.5 with angular upgrade was published to npm and now set as latest.
