### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by daniel-seitz** [microsoft/powerbi-client-angular#29]
According to [the docs](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/refresh-token) we have to implement functionality to refresh the token automatically.

Is there / do you / could you have any plans to implement this functionality on this package?

Would be nice if we could subscribe to a method in this package instead of everyone writing their own manual solution.

**Comment by jaspreet1234567** [comment]
@daniel-seitz  - Did you find any solution to this?

**Comment by daniel-seitz** [comment]
@jaspreet1234567 yes, I wrote it myself. Take the time of issuance, +1h, I subtracted some minutes and request a new token then.

**Comment by daniel-seitz** [comment]
Ok, the whole process:

     <powerbi-report
        [embedConfig]="embedConfig"
        [cssClassName]="'embedded-report'"
        [phasedEmbedding]="false"
        [eventHandlers]="eventHandlers"
        ></powerbi-report>

we hook into the rendered event:

    get eventHandlers(): Map<string, EventHandler|null> {
        return new Map([
          ['loaded', () => { ... }],
          ['pageChanged', (event: any) => { ... }],
          ['rendered', () => {
    // HERE
          }],
          ['error', (error: any) => { ...  }]
        ])

Of course, instead of  `HERE` we call a function (that also gets called on the document:visibilitychanged event - when the tab is switched to and showing the report again.)

the logic is somehow like this:
    - check expiration of current token
    - calculate expiration - minutesBeforeTokenExpiry
    - if now is before that, then get a new refresh token (like you did initially as well)
    - replace the embedConfig.accessToken with the new token

Thats it.

**Regarding your answer:**
You just need to replace the embedConfig with a new reference, not just update the accessToken property.

**Comment by jaspreet1234567** [comment]
Thanks @daniel-seitz for the quick response and solution. Will try it and let you know. I think it will work.

**Comment by jaspreet1234567** [comment]
Hi @daniel-seitz - Regarding your text:
**You just need to replace the embedConfig with a new reference, not just update the accessToken property.**

Do we just need to update the access token property like: **embedConfig.accessToken** with new token OR need to create new embedConfig object and assign again to Input property like: **[embedConfig]="embedConfig"**

**Comment by jameswiseman76rlg** [comment]
@daniel-seitz Is the 'rendered' event robust and sufficient enough, and work under scrutiy? How does it work if the token has already expired? Surely, the report will fail to load and we'll never render it?

**Comment by v-MadhavC** [comment]
To automatically refresh the access token, you can use the `eventHooks` configuration and set the `accessTokenProvider` function in the embedding parameters. This function will be triggered when the token is close to expiring, allowing you to generate and assign a fresh token to the embedded report.

```
const getNewAccessToken = async () => {
    // Code you need to add for generating new token
    return token;
};
 
const config = {
    type: 'report',
    tokenType: models.TokenType.Aad,
    accessToken: "initial token", 
    embedUrl: "Your report's embed URL",
    eventHooks: {
        accessTokenProvider: getNewAccessToken
    }
};

```
For more details you can refer to this documentation: [Refresh the access token in Power BI embedded analytics | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/refresh-token#automatically-refresh-token)
