### ISSUE TITLE
Pass click event outside

### ISSUE THREAD

**Issue by daniel-seitz** [microsoft/powerbi-client-angular#30]
Tried to listen for the click even: (click)="callMyMethod" but this is never called, guessing there is a stopPropagation in place somewhere inside.

Using report.on('click'... does not work and gives an error since its not defined in the available events.

Our workaround is to listen for the rendered event but a normal click would be better.

This feature is especially interesting when the app has a inactivity timeout and working inside the report needs to reset the countdown. Also I could think of other scenarios when the app needs to react when something is done inside.

Please consider / give feedback on this matter.
Thank you, Daniel

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is a feature request, please add it in the following link where we can collect votes: https://ideas.fabric.microsoft.com . If the feature is already there, you can add a vote.
