### ISSUE TITLE
reportObj always returns `undefined`

### ISSUE THREAD

**Issue by mohsinjamadar** [microsoft/powerbi-client-angular#31]
I have tried the demo code

Tried to use reportObj by two ways

1.  Expose the Report object globally - didn't worked
2. Use reportObj inside a class method - didn't worked

Even I tried to setTimeout of say 20 seconds. still reportObj is undefined.

I am sure I am missing something from the documentation.

please help

**Comment by kkd1215** [comment]
Hello @mohsinjamadar,
You can refer to the official documentation [here](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/powerbi-client-angular) and try following the README as well. If you are still facing some issues, please share the some more details.
