### ISSUE TITLE
Support for Scorecards

### ISSUE THREAD

**Issue by jdmoore1618** [microsoft/powerbi-client-angular#32]
Hello,

Is there something on the roadmap to support embedding Scorecards? 

Thanks

**Comment by KotanaSai21** [comment]
There's no official documentation on embedding Scorecards, to support in our package. Not sure, with the plan to officially announce scorecard embeddings.  You can submit the idea here [Power BI Ideas](https://ideas.powerbi.com/ideas/).

However, there is a workaround if you want to embed scorecard using `powerbi-client-angular` is to embed as type report. Refer to [Embed Power BI Goals in your app - Microsoft Power BI Community](https://community.powerbi.com/t5/Community-Blog/Embed-Power-BI-Goals-in-your-app/ba-p/2001107)

Feel Free to Reach out if you have any other queries.

**Comment by KotanaSai21** [comment]
There's no official documentation on embedding Scorecards, to support in our package. No plan yet to officially announce scorecard embeddings. You can submit the idea here [Power BI Ideas](https://ideas.powerbi.com/ideas/).

However, there is a workaround if you want to embed scorecard using powerbi-client-angular is to embed as type report. Refer to [Embed Power BI Goals in your app - Microsoft Power BI Community](https://community.powerbi.com/t5/Community-Blog/Embed-Power-BI-Goals-in-your-app/ba-p/2001107)

Feel Free to Reach out if you have any other queries :)

**Comment by jdmoore1618** [comment]
Thanks, I will submit the idea.
