### ISSUE TITLE
Table scroll bars are not visible in Google Chrome

### ISSUE THREAD

**Issue by Semptra** [microsoft/powerbi-client-angular#37]
In the embedded report, scroll bars for the `Table` are now visible in Google Chrome.
In Firefox, scroll bars are visible.

---

Example:

Report in Power BI Workspace

![image](https://user-images.githubusercontent.com/43088712/227920645-c942fd92-b337-4a08-adb4-c6dde877ca1d.png)

Report in Power BI Embedded

![image](https://user-images.githubusercontent.com/43088712/227921183-b2095193-6aed-42c4-8993-cbbdb5050b64.png)

---

However, I have found that if I apply the following configuration to the report, it magically fixes the problem:

```typescript
settings: {
    layoutType: models.LayoutType.Custom,
    customLayout: {
        pagesLayout: {
              '': { visualsLayout: { '': { } } }
        }
    }
 }
```

---

System information.
Angular version - 11
powerbi-client-angular version - 2.0.0
Google Chrome version - 111.0.5563.111 (Official Build) (64-bit)

**Comment by KotanaSai21** [comment]
Unable to repro the issue with the same versions. Might be report specific. Please share further information or contact [Power BI Support.](https://powerbi.microsoft.com/support/)

**Comment by Semptra** [comment]
@KotanaSai21 thanks for checking this out, I've been able to find an issue on my side. For more info, you can check my question on SO (and maybe verify it and include this in your docs) - https://stackoverflow.com/questions/75855445/table-scroll-bars-are-not-visible-in-power-bi-embedded-google-chrome
