### ISSUE TITLE
Missing fonts and styles in power bi embedded reports

### ISSUE THREAD

**Issue by skapoor8** [microsoft/powerbi-client-angular#42]
I'm experiencing a somewhat bizarre issue with missing fonts and styles in power bi embedded. I've managed to embed my report properly, however the appearance of the report is different from what I'm seeing in power bi desktop and online.

As an example, this is one of the visuals from my report in power bi online:

![Screen Shot 2023-06-29 at 12 00 29 PM](https://github.com/microsoft/powerbi-client-angular/assets/14297543/127a7c6c-50f2-4a86-aa4a-71ef6d6c05dc)

Here's the same visual when it's actually embedded in an angular application:

![Screen Shot 2023-06-29 at 12 03 04 PM](https://github.com/microsoft/powerbi-client-angular/assets/14297543/b9135914-6248-4685-a2ec-08c5e250834b)

As you can see, the font in the visual title is switched from Segoe UI to Times New Roman, and the spacing of the visual is changed. The content near the bottom is overflowing the bounds of the visual. This issue happens across many visuals, and which visual's fonts and styles are dropped appears to be quite random. 

I should mention we are not using any custom fonts. I suspect that this issue might be stemming from us being in development, and not having a dedicated power bi capacity. It's possible the MS is throttling requests on their end, leading to some js bundles being dropped which could lead to the missing styles and fonts. However, I would like to confirm this as our decision to go ahead and pay for a power bi embedded capacity is contingent on whether the styling of the reports will be as expected.

Any help on this issue would be greatly appreciated! I'm quite stumped since this issue does not seem to be coming up on GitHub issues or MS support pages.

**Comment by v-MadhavC** [comment]
We have tried to reproduce the issue you described. However, in our case, the fonts and styles remain unchanged even after embedding the report using the package.
For better understanding, could you kindly provide more details about the specific visual for which the fonts and styles are not displaying correctly? Is it a Power BI Custom visual, or is it one of the default visuals?
