### ISSUE TITLE
FrontLoadException conceptualSchema Exception: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sturlath** [microsoft/powerbi-client-angular#46]
Since its not possible to create issues in the [powerbi-client repo](https://github.com/microsoft/PowerBI-JavaScript) I'm creating this here.

I'm trying to **embed PowerBI** in **Blazor Server** components **within an Angular project**. See this project, [BlazorCustomElements](https://github.com/danroth27/BlazorCustomElements) 

I'm getting the following exception

> Uncaught (in promis) "FrontLoadException" "conceptualSchema Exception: Unexpected end of JSON input"

![image](https://github.com/microsoft/powerbi-client-angular/assets/2386572/1e26403d-c508-462b-bc28-2fba1d112c90)

[This is the C# code that is calling the javascript](https://github.com/sturlath/AngularBlazorProject/blob/65c86f1f21667fa1ebc3fe6da66790a696f7ecda/BlazorWrapperApp/Components/PowerBI.razor#L22) and [this is the powerBI embed Javascript in the Angular](https://github.com/sturlath/AngularBlazorProject/blob/65c86f1f21667fa1ebc3fe6da66790a696f7ecda/BlazorWrapperApp/ClientApp/src/assets/powerbiInterop.js#L23C16-L23C16)

I don´t think its related but [there is an error when I run the project](https://github.com/danroth27/BlazorCustomElements/issues/2)

**Comment by v-MadhavC** [comment]
We cloned the repository that you provided.

Here are the steps that we followed:

1. Run the application which was in the repository.
2. Passed the config for the report to be embedded.
3. The report was embedded without any issue. Did not get the error of Uncaught (in promis) "FrontLoadException" "conceptualSchema Exception: Unexpected end of JSON input"

Snapshot of the running application with the embedded report for reference:

![Image](https://github.com/user-attachments/assets/c9365ec4-2c28-44ba-bc56-0862c7a50e3a)

Please let us know whether you are still facing the same issue or if there are any specific steps we need to follow.

**Comment by sturlath** [comment]
Great to see that you got this to work. We have put this work on ice for now. We were looking into starting to do Blazor development without loosing any work in the Angular space. We can just close this..
