### ISSUE TITLE
Optimization Npm Builed Failed when adding powerbi-client-angular in our Angular 16 app

### ISSUE THREAD

**Issue by oliviercochet** [microsoft/powerbi-client-angular#51]
Hello,
is there a way to manage bundles and optimization process with the adding off powerbi-client-angular.

Since we add this module our build failed from JS Heap out of size despite increasing the memory associated

**Comment by KotanaSai21** [comment]
We investigated the issue but we're not able to reproduce the issue. We tried running the optimization building process in our application by running npm build command and it worked fine.

Please provide more details to investigate this issue.

**Comment by oliviercochet** [comment]
Hi to all,
We've been struggling with our build with OLD CommonJS dependencies like this module.
Finally we use LazyLoading Module in order to seperate build and then reduce the heap size for each build.

Thanks for you testing.
Hope that this will help others.
