### ISSUE TITLE
Want to send additional parameters with request which we made to get the report

### ISSUE THREAD

**Issue by jaspreet1234567** [microsoft/powerbi-client-angular#52]
Is there any way to send the additional parameters with request which we made to get the report. In our case we have to send the logged in user email with request.

Thanks in advance.

**Comment by KotanaSai21** [comment]
Use [Get Report In Group](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group) REST API to get the report details. While hitting the API you can authenticate using either a Bearer Token or username and password credentials. 

Could you please provide additional details for better understanding the issue?

**Comment by jaspreet1234567** [comment]
Hi @KotanaSai21  - I achieved this by using the Row-Level-Security. This is the link I follow to pass the user-email:
[Implementing row-level security in embedded paginated reports](https://learn.microsoft.com/en-us/power-bi/developer/embedded/paginated-reports-row-level-security)
