### ISSUE TITLE
Warning CommonJS or AMD dependencies

### ISSUE THREAD

**Issue by bizappzone** [microsoft/powerbi-client-angular#57]
Currently getting a warning when running application 

'powerbi-client'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Added configs as instructed above 
    "build": {
      "executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
...
        "allowedCommonJsDependencies": [ "powerbi-client-angular"],

**Comment by v-MadhavC** [comment]
To address the warning, it is recommended to include the problematic package in the 'allowedCommonJsDependencies' array within your angular.json file. By doing so, Angular will recognize the package as safe for use as a CommonJS dependency, resolving the warning.  

For further clarification, you may refer to the documentation - [CommonJS or AMD dependencies can cause optimization bailouts | bobbyhadz](https://bobbyhadz.com/blog/angular-commonjs-or-amd-dependencies-can-cause-optimization-bailouts) 

If the issue still exists please provide more details.

**Comment by v-MadhavC** [comment]
The warning originates from the `powerbi-client`, package. To resolve this, update the `allowedCommonJsDependencies` option in your build configuration to prevent the CommonJS dependency warnings:

```
 "allowedCommonJsDependencies": [
     "powerbi-client"
 ],
```
