### ISSUE TITLE
NaN issues while using zoom sliders on the visuals

### ISSUE THREAD

**Issue by jainanuj0812** [microsoft/powerbi-client-angular#58]
Hi 

I am getting this weird issue while embedding the powerbi report on the angular webapp. After applying filters the visual is not generated correctly and clicking on it will make the visual appear.

This is happening with the powerbi visual containing the zoom slider on the date.

Here is the screen shot for the same

<img width="1150" alt="Screenshot 2024-02-22 at 11 25 43 AM" src="https://github.com/microsoft/powerbi-client-angular/assets/9433435/4d6f56c0-be7c-45a3-a3fe-404a87e7874a">

After clicking

<img width="1150" alt="Screenshot 2024-02-22 at 11 25 48 AM" src="https://github.com/microsoft/powerbi-client-angular/assets/9433435/74d90a41-3180-4df7-8cea-dbb6e0cf01b9">

**Comment by KotanaSai21** [comment]
@jainanuj0812 , Could you confirm if this behavior is only with the embedded report. 
Can you once check, if the report in PBI service works fine after applying filters?

**Comment by jainanuj0812** [comment]
@KotanaSai21 

Yup the reports works fine on PBI Service. This is for embedded reports only

**Comment by v-MadhavC** [comment]
We tried reproducing the issue that you are facing.  Here are the steps that we followed: 

1. Created a visual of 'line and clustered column chart' with the zoom slider on the date. 
2. Followed the steps for embedding the report in the angular webapp.  

The visual is getting rendered correctly irrespective of any filters applied or not. 

Before Filters: 
![GetImage](https://github.com/microsoft/powerbi-client-angular/assets/126773262/0760a1cd-37da-4f1e-bdeb-a9021f543f3d)

After Filters: 
![GetImage (1)](https://github.com/microsoft/powerbi-client-angular/assets/126773262/0ceeee55-c666-4173-92be-c186ef6618aa)
Please provide more details to help us repro the issue.

**Comment by jainanuj0812** [comment]
Hi,

Not sure the demo report I have added works for me, but not with the above actual reports. Might be some data discrepancy.

For now I have called refresh once for the report to get load properly.

Meanwhile I will share the repo somehow with you to look into it
