### ISSUE TITLE
cannot install power bi angular in Angular 10.0.3version and node 16v

### ISSUE THREAD

**Issue by aarthikarike** [microsoft/powerbi-client-angular#62]
Hi Team,

My project is running on Angular 10.0.3v and node js 16v, when I am trying to install power Bi client angular facing challenges due to version compatibilities, so I tried to install lower versions of power Bi angular 1.0.1version yet it is not installing. Most of the solutions I got to upgrade Angular >=12v to make it work however I am afraid we will face deprecation issues or any dependency issues if we upgrade. 
Tried to approach Microsoft community support and npm support no solution until now. can anyone guide how to approach better solution. Tried to upgrade google tag manager as per the error still same.

 npm i -g powerbi-client-angular@1.0.1
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 13 packages, and audited 14 packages in 17s

found 0 vulnerabilities
 npm i  powerbi-client-angular        
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: angular-google-tag-manager@1.4.2
npm ERR! Found: @angular/common@10.0.14
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"10.0.14" from @angular/forms@10.0.14
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"~10.0.4" from the root project
npm ERR!   peer @angular/common@"10.0.14" from @angular/platform-browser@10.0.14
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     peer @angular/platform-browser@"10.0.14" from @angular/forms@10.0.14
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"~10.0.4" from the root project
npm ERR!     peer @angular/platform-browser@"10.0.14" from @angular/platform-browser-dynamic@10.0.14
npm ERR!     node_modules/@angular/platform-browser-dynamic
npm ERR!       @angular/platform-browser-dynamic@"~10.0.4" from the root project
npm ERR!     3 more (@angular/router, ngx-image-cropper, the root project)
npm ERR!   5 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.3" from angular-google-tag-manager@1.4.2
npm ERR! node_modules/angular-google-tag-manager
npm ERR!   angular-google-tag-manager@"^1.4.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@12.2.17
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^12.0.3" from angular-google-tag-manager@1.4.2
npm ERR!   node_modules/angular-google-tag-manager
npm ERR!     angular-google-tag-manager@"^1.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Ammagari.Sathyanand\AppData\Local\npm-cache\eresolve-report.txt for a full report.       

npm ERR! A complete log of this run can be found in:
npm ERR!

**Comment by v-MadhavC** [comment]
The library supports Angular applications having version >= 13.

Please refer the [Note section in Readme.md](https://github.com/microsoft/powerbi-client-angular#note) for this library.

Feel free to reach out for any other queries.
