### ISSUE TITLE
demo app is not working CORS issues

### ISSUE THREAD

**Issue by FirassKoubaa** [microsoft/powerbi-client-angular#65]
then demo app is not working properly on localhost due to CORS issues:

![image](https://github.com/microsoft/powerbi-client-angular/assets/12677901/35424220-40a5-4003-bdf8-6e70883f9146)

**Comment by v-MadhavC** [comment]
Thank you for reporting this issue. This is an old issue, is it still relevant?

**Comment by v-MadhavC** [comment]
We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed

**Comment by ayeshurun** [comment]
The issue is closed since no response was received.
