### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tokenType')

### ISSUE THREAD

**Issue by StephanBis** [microsoft/powerbi-client-angular#66]
Hi,

We're getting the following error when trying to embed a report. 

```
TypeError: Cannot read properties of undefined (reading 'tokenType')
    at isSaaSEmbedWithAADToken (reportEmbed?navContentPaneEnabled=false&uid=ame7c8:586:38)
    at getModelsAndExploration (reportEmbed?navContentPaneEnabled=false&uid=ame7c8:696:17)
    at getModelsAndExplorationAndConceptualSchema (reportEmbed?navContentPaneEnabled=false&uid=ame7c8:840:9)
    at xhr.onreadystatechange (reportEmbed?navContentPaneEnabled=false&uid=ame7c8:505:37)
```
```
this.msalService.initialize().subscribe(() => {
      this.msalService.acquireTokenSilent({
        scopes: environment.powerBiConfig.scopes,
        account: this.authService.getUser()
      }).subscribe(async (result) => {
        const embedConfig: pbi.service.IComponentEmbedConfiguration = {
          type: 'report',
          id: this.report.identifier,
          accessToken: result.accessToken,
          tokenType: models.TokenType.Aad,
          embedUrl: 'https://app.powerbi.com/reportEmbed?navContentPaneEnabled=false',
          settings: {
            panes: {
              filters: {
                visible: false,
              }
            }
          }
        };
        const defaultFilters = this.createDefaultFilters();
        const powerBiReport: any = this.powerBiService.embed(this.reportContainer.nativeElement, embedConfig);
        powerBiReport.on('loaded', async () => {
          await powerBiReport.setFilters(defaultFilters);
        });
      });
    });
```

This setup has been working great for a while, but after switching up some code, this error started occuring. This block of code has been moved to AfterViewInit, we already tried moving it back to OnInit, but the issues stays. Does anyone have a clue?

**Comment by vsmakagenzeon** [comment]
We are encountering a similar error when embedding the report, specifically receiving an "undefined method config" error message. This issue has recently surfaced, and it appears that the config parameter is not being passed to the isSaaSEmbedWithAADToken() function, which seems to be causing the error. 
Does anyone have any ideas on how to fix this issue? Is this a problem that needs to be resolved on the Power BI side?

**Comment by vsmakagenzeon** [comment]
We are encountering a similar error when embedding the report, specifically receiving an "undefined method config" error message. This issue has recently surfaced, and it appears that the config parameter is not being passed to the isSaaSEmbedWithAADToken() function, which seems to be causing the error. Does anyone have any ideas on how to fix this issue? Is this a problem that needs to be resolved on the Power BI side?

**Comment by smartclue** [comment]
I does appear that this would be something caused by changes in the power bi side of things. Looking at the demo playground app for the embedded BI also seems to be encountering this failure.

https://playground.powerbi.com/en-us/showcases-gallery/insight-to-action

This error appears to be non-fatal for version of chromium 94+. The same can not be said about older versions, if you are running a regression that is using older browser versions your embedded report might not load.

**Comment by StephanBis** [comment]
> I does appear that this would be something caused by changes in the power bi side of things. Looking at the demo playground app for the embedded BI also seems to be encountering this failure.
> 
> https://playground.powerbi.com/en-us/showcases-gallery/insight-to-action
> 
> This error appears to be non-fatal for version of chromium 94+. The same can not be said about older versions, if you are running a regression that is using older browser versions your embedded report might not load.

You are correct, this error is non-fatal on later version of Chromium. We were facing a different issue which caused the reports to not load. This does need to be fixed at Microsoft's end.

**Comment by aliabufoul** [comment]
Thanks for reporting this issue.
The issue was fixed. Fix should be deployed by this week.

**Comment by sshresthareach** [comment]
> > I does appear that this would be something caused by changes in the power bi side of things. Looking at the demo playground app for the embedded BI also seems to be encountering this failure.
> > https://playground.powerbi.com/en-us/showcases-gallery/insight-to-action
> > This error appears to be non-fatal for version of chromium 94+. The same can not be said about older versions, if you are running a regression that is using older browser versions your embedded report might not load.
> 
> You are correct, this error is non-fatal on later version of Chromium. We were facing a different issue which caused the reports to not load. This does need to be fixed at Microsoft's end though.

I am assuming a fix has been deployed. Looks like the error does not appear anymore but the embedded reports still do not load in chromium versions older than 94.

**Comment by andy-peoples** [comment]
> Thanks for reporting this issue. The issue was fixed. Fix should be deployed by this week.

Hi, 
we too are experiencing the same issue running Chromium 92. It is not currently possible to upgrade to a higher version.
Do we need to amend any code on our side?

**Comment by StephanBis** [comment]
Issue has been fixed at Microsoft's end.
