### ISSUE TITLE
Invalid embed URL detected. Either URL hostname or protocol are invalid. Please use Power BI REST APIs to get the valid URL

### ISSUE THREAD

**Issue by rjculaway** [microsoft/powerbi-client-angular#74]
Hello, 

I started getting this error after upgrading to Angular 17.

`Invalid embed URL detected. Either URL hostname or protocol are invalid. Please use Power BI REST APIs to get the valid URL`

I tried this solution https://github.com/microsoft/powerbi-client-angular/issues/60 but i still get the same error.

here are the versions i currently use

"powerbi-client": "^2.23.1",
"powerbi-client-angular": "^3.0.5",

![Image](https://github.com/user-attachments/assets/4de44081-9e9b-45d4-9dd0-bacf84d7742d)

Some additonal info:  We are not using the cloud version of PowerBI  - anyway this was working fine before the Angular upgrade

Thank you so much!

**Comment by v-MadhavC** [comment]
We're closing GitHub issues on 01/01/2025.

Please continue to share your feedback and get support through these channels:

- **Feature Requests**: Submit your ideas and suggestions to the [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/), where you can also vote on ideas from other developers.

- **Bug Reports and Technical Assistance**: Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
 
- **Additional Support**: Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).

We highly value your contributions and look forward to collaborating with you to enhance our offerings based on your feedback.

Thank you,

**The Power BI Embedded Team**
