### ISSUE TITLE
Some thing went wrong when loading embed power bi report using angular in Edge browser.

### ISSUE THREAD

**Issue by gokulb97** [microsoft/powerbi-client-angular#75]
Hi,
Some thing went wrong popup is showing  when loading embed power bi report using angular in Edge browser. 
The report are loading in background but this error popup is showing.

![Image](https://github.com/user-attachments/assets/46b77827-8770-4074-8009-e2676fae6c51)

**Comment by darshanK72** [comment]
I am also facing same issue. but it is happening in chrome as well.
