### ISSUE TITLE
Getting Page Expired Error

### ISSUE THREAD

**Issue by sachinmishra007** [microsoft/powerbi-client-angular#77]
Hi Team,

I am following embed for organization approach using AAD and I am using `powerbi-client-angular`
library, I have started getting the below error. Can you please tell me how to get rid of it ?

I am doing refresh token as soon as it is expired using MSAL and also added accesstoken hook for getting token

![Image](https://github.com/user-attachments/assets/ebb51802-a893-4c50-ae27-75dd4e5c9687)

**Comment by ayeshurun** [comment]
We're closing GitHub issues on 01/01/2025.

**Please continue to share your feedback and get support through these channels:**

- **Feature Requests:** Submit your ideas and suggestions to the [Fabric Ideas Portal](https://ideas.fabric.microsoft.com/), where you can also vote on ideas from other developers.
- **Bug Reports and Technical Assistance:** Visit the [Fabric Developer Community Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer). Our team and community experts are ready to assist you.
- **Additional Support:** Contact your account manager or reach out to the [Fabric Support Team](https://support.fabric.microsoft.com/en-us/support/).

We highly value your contributions and look forward to collaborating with you to enhance our offerings based on your feedback.

Thank you,
**The Power BI Embedded Team**
