### ISSUE TITLE
Add list of events supported by eventHandler in the Docs/Readme

### ISSUE THREAD

**Issue by Vignesh-Ganesan-008** [microsoft/powerbi-client-angular#9]
**Hey Guys, could you add the list of events supported by eventHandler in the Docs/ Readme.** 
In the project I'm working in, we used the powerbi-report component and we needed a clicklistener on it, I tried it the angular way and couldn't get it to work (was stuck on this for a long time) and after some digging I came across the "visualClicked" event in the demo application here and using that it works. So it would be helpful if you guys can just add a list of all the events supported by eventHandler somewhere in the docs or readme.

Thanks

**Comment by may-hartov** [comment]
Supported events are now documented in readme: https://github.com/microsoft/powerbi-client-angular/blob/main/README.md#supported-events
